project:
  type: book
  output-dir: _book

book:
  title: "`repliMAT`: *A* Guide to Reproducible MATLAB"
  author: "David Wilby"
  date: "last-modified"
  date-format: "D MMM, YYYY"
  chapters:
    - index.qmd
    - intro.qmd
    - part: code-style/index.qmd
      chapters: 
        - code-style/variables.qmd
        - code-style/functions.qmd
        - code-style/organisation.qmd
        - code-style/documentation.qmd
    - part: reproducibility/index.qmd
      chapters: 
        - reproducibility/projects.qmd
    - part: exercises/index.qmd
      chapters: 
        - exercises/getting-started.qmd
    - part: extra-credit/index.qmd
      chapters: 
        - extra-credit/testing.qmd
        - extra-credit/version-control.qmd
  appendices:
    - appendices/code-style-cheatsheet.qmd
    - references.qmd
    - _license.qmd
    - privacypolicy.qmd
  sidebar: 
    tools:
      - icon: github
        href: https://github.com/reproducibleMATLAB/reproducibleMATLAB.github.io
        aria-label: GitHub
        target: _blank
      - icon: chat-right-text-fill
        href: https://reproducibleMATLAB.github.io/blog
        aria-label: Blog
        target: _blank
  google-analytics: 
    tracking-id: "G-WMTSZ2TVF9"
    anonymize-ip: true
    storage: none

bibliography: references.bib
csl: nature.csl

format:
  html:
    from: markdown+emoji
    theme: 
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt



